// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoShop.Data;

#nullable disable

namespace PhotoShop.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231201140655_AddOrderAndOrderLineEntities")]
    partial class AddOrderAndOrderLineEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoShop.Models.Domin.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PhotoShop.Models.Domin.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLine");
                });

            modelBuilder.Entity("PhotoShop.Models.Domin.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a59022e-de98-41f2-ba0b-42233fab3664"),
                            Description = "This is Photo Nr 1 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/74/500",
                            Price = 202m,
                            Title = "Photo 1"
                        },
                        new
                        {
                            Id = new Guid("4efb9c99-0553-471c-a4ff-356e52f23dcc"),
                            Description = "This is Photo Nr 2 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/70/500",
                            Price = 593m,
                            Title = "Photo 2"
                        },
                        new
                        {
                            Id = new Guid("b755145f-728e-4652-8cba-70db836c9237"),
                            Description = "This is Photo Nr 3 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/80/500",
                            Price = 944m,
                            Title = "Photo 3"
                        },
                        new
                        {
                            Id = new Guid("6c44180e-44f6-41d6-b977-6e642b035f6e"),
                            Description = "This is Photo Nr 4 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/57/500",
                            Price = 911m,
                            Title = "Photo 4"
                        },
                        new
                        {
                            Id = new Guid("560d86da-6cc7-48ab-aeed-9644170a0d55"),
                            Description = "This is Photo Nr 5 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/67/500",
                            Price = 665m,
                            Title = "Photo 5"
                        },
                        new
                        {
                            Id = new Guid("98af687b-9d6c-449c-92db-8d924445a3c3"),
                            Description = "This is Photo Nr 6 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/83/500",
                            Price = 160m,
                            Title = "Photo 6"
                        },
                        new
                        {
                            Id = new Guid("d3811ece-6e97-4b93-84be-fd64c968190e"),
                            Description = "This is Photo Nr 7 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/30/500",
                            Price = 524m,
                            Title = "Photo 7"
                        },
                        new
                        {
                            Id = new Guid("cdff9acc-728e-4340-b0ca-a868fbb42226"),
                            Description = "This is Photo Nr 8 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/72/500",
                            Price = 401m,
                            Title = "Photo 8"
                        },
                        new
                        {
                            Id = new Guid("1bd468db-58f9-4f7a-83cc-b7c75949c062"),
                            Description = "This is Photo Nr 9 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/58/500",
                            Price = 729m,
                            Title = "Photo 9"
                        },
                        new
                        {
                            Id = new Guid("dea1c565-d530-48c6-8f71-714a62bd2a1d"),
                            Description = "This is Photo Nr 10 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/16/500",
                            Price = 697m,
                            Title = "Photo 10"
                        });
                });

            modelBuilder.Entity("PhotoShop.Models.Domin.OrderLine", b =>
                {
                    b.HasOne("PhotoShop.Models.Domin.Order", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("PhotoShop.Models.Domin.Order", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
