// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoShop.Data;

#nullable disable

namespace PhotoShop.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231204115059_AddQuantityPropToOrderLine")]
    partial class AddQuantityPropToOrderLine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoShop.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PhotoShop.Models.Domain.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLine");
                });

            modelBuilder.Entity("PhotoShop.Models.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("719d7d3f-9ab0-4d12-abaf-3db0fc837eec"),
                            Description = "This is Photo Nr 1 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/41/500",
                            Price = 473m,
                            Title = "Photo 1"
                        },
                        new
                        {
                            Id = new Guid("c4858f61-9283-4fa3-914b-3ed496fdb304"),
                            Description = "This is Photo Nr 2 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/81/500",
                            Price = 530m,
                            Title = "Photo 2"
                        },
                        new
                        {
                            Id = new Guid("8e9941f9-cee8-488d-9965-16eb4c79e623"),
                            Description = "This is Photo Nr 3 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/53/500",
                            Price = 626m,
                            Title = "Photo 3"
                        },
                        new
                        {
                            Id = new Guid("89c52d5c-a6ea-40e2-ae6a-bb89d98f29fa"),
                            Description = "This is Photo Nr 4 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/12/500",
                            Price = 557m,
                            Title = "Photo 4"
                        },
                        new
                        {
                            Id = new Guid("99d5f1d0-4cf8-4635-ba6f-5750b9ae380e"),
                            Description = "This is Photo Nr 5 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/53/500",
                            Price = 936m,
                            Title = "Photo 5"
                        },
                        new
                        {
                            Id = new Guid("c2aaa285-af90-4d5a-9e16-74859470d41e"),
                            Description = "This is Photo Nr 6 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/85/500",
                            Price = 426m,
                            Title = "Photo 6"
                        },
                        new
                        {
                            Id = new Guid("76e2fd69-ed0f-473b-b681-6858dbde3ba9"),
                            Description = "This is Photo Nr 7 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/7/500",
                            Price = 623m,
                            Title = "Photo 7"
                        },
                        new
                        {
                            Id = new Guid("7e047aeb-b436-40f6-adde-4e1dffe4e977"),
                            Description = "This is Photo Nr 8 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/34/500",
                            Price = 426m,
                            Title = "Photo 8"
                        },
                        new
                        {
                            Id = new Guid("200d5b92-d551-41d6-ba06-4f44b5355220"),
                            Description = "This is Photo Nr 9 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/63/500",
                            Price = 765m,
                            Title = "Photo 9"
                        },
                        new
                        {
                            Id = new Guid("33eead55-b609-4a62-9b1e-01b46b6b9765"),
                            Description = "This is Photo Nr 10 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/35/500",
                            Price = 221m,
                            Title = "Photo 10"
                        });
                });

            modelBuilder.Entity("PhotoShop.Models.Domain.OrderLine", b =>
                {
                    b.HasOne("PhotoShop.Models.Domain.Order", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("PhotoShop.Models.Domain.Order", b =>
                {
                    b.Navigation("OrderLines");
                });
#pragma warning restore 612, 618
        }
    }
}
