// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoShop.Data;

#nullable disable

namespace PhotoShop.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoShop.Models.Domin.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2be14327-e257-4398-bf3c-0090be2e60ed"),
                            Description = "This is Photo Nr 1 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/41/500",
                            Price = 672m,
                            Title = "Photo 1"
                        },
                        new
                        {
                            Id = new Guid("c1673ae3-2a37-48ec-93c0-80aefd318e69"),
                            Description = "This is Photo Nr 2 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/45/500",
                            Price = 600m,
                            Title = "Photo 2"
                        },
                        new
                        {
                            Id = new Guid("69f2e429-d6be-4125-ac4a-d2286a15ef26"),
                            Description = "This is Photo Nr 3 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/11/500",
                            Price = 349m,
                            Title = "Photo 3"
                        },
                        new
                        {
                            Id = new Guid("7bd257b0-e33a-4fbc-a8d4-ca98fb330857"),
                            Description = "This is Photo Nr 4 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/59/500",
                            Price = 810m,
                            Title = "Photo 4"
                        },
                        new
                        {
                            Id = new Guid("a6fd6dc6-5781-430c-9c53-e26482e26607"),
                            Description = "This is Photo Nr 5 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/7/500",
                            Price = 964m,
                            Title = "Photo 5"
                        },
                        new
                        {
                            Id = new Guid("22ca08b5-2403-4eec-8197-9834c85ce94a"),
                            Description = "This is Photo Nr 6 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/12/500",
                            Price = 191m,
                            Title = "Photo 6"
                        },
                        new
                        {
                            Id = new Guid("c32a6579-a643-4cd2-afd0-ab5d90f44c0f"),
                            Description = "This is Photo Nr 7 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/37/500",
                            Price = 363m,
                            Title = "Photo 7"
                        },
                        new
                        {
                            Id = new Guid("79b7e0b3-28f9-46a6-8769-05730bb19982"),
                            Description = "This is Photo Nr 8 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/40/500",
                            Price = 142m,
                            Title = "Photo 8"
                        },
                        new
                        {
                            Id = new Guid("2e3f47f7-c98e-4454-b860-4072c0d0741e"),
                            Description = "This is Photo Nr 9 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/65/500",
                            Price = 751m,
                            Title = "Photo 9"
                        },
                        new
                        {
                            Id = new Guid("334f6548-c7d0-438e-bbdb-3f4fde6b642e"),
                            Description = "This is Photo Nr 10 in our collection of photographs.",
                            ImageUrl = "https://picsum.photos/id/68/500",
                            Price = 91m,
                            Title = "Photo 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
